version: "3.8"

services:
  api:
    build: .
    environment:
      - DEV_MODE=true
      - MONGO_URL=mongodb://guest:guest@mongo:27017/
      - DATABASE_NAME=chat
      - JWT_SECRET=f5d9e7a587e6efbbbb8efbe71e6dd1f42cd6f040
      - JWT_TTL=3600
      - SERVER_PORT=8080
      - WEBSOCKET_READ_BUFFER_SIZE=1024
      - WEBSOCKET_WRITE_BUFFER_SIZE=1024
      - RABBITMQ_DSN=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_STOOQ_RECEIVER_QUEUE=stock-result
      - RABBITMQ_STOOQ_PUBLISHER_QUEUE=stock-process-request
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
      - mongo
    links:
      - rabbitmq
      - mongo
    networks:
      - api_network
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    volumes:
      - /var/lib/rabbitmq
    ports:
      - 15671:15671
      - 15672:15672
      - 25672:25672
      - 5671:5671
      - 5672:5672
    networks:
      - api_network
    restart: on-failure

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=guest
      - MONGO_INITDB_ROOT_USERNAME=guest
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - /data/configdb
      - /data/db
    ports:
      - 27017:27017
    networks:
      - api_network
    restart: on-failure

networks:
  api_network:
    driver: bridge
